baseURL = 'https://kiranandcode.github.io/nyc-category-theory-website/'
languageCode = 'en-us'
title = 'NYC Category Theory Reading Club'

[params]
  description = "NYC Beginners-friendly Category Theory Reading Club"
  discordURL = "https://discord.gg/NWGdjJ6nJJ"
  meetupURL = "https://www.meetup.com/nyc-beginners-friendly-category-theory-reading-club-awodey/"
  lumaURL = "https://luma.com/nyccat"
  personalSiteURL = "https://kirancodes.me"
  bookTitle = "Seven Sketches in Compositionality"
  bookSubtitle = "An Invitation to Applied Category Theory"
  bookAuthor = "Brendan Fong and David Spivak"
  bookURL = "https://arxiv.org/abs/1803.05316"
  previousBookTitle = "Category Theory"
  previousBookAuthor = "Steve Awodey"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
